### ISSUE TITLE
card/groovy script file name should not contain hyphen '-'

### ISSUE THREAD

**Issue by melvinzhang** [firemind/ProjectFiremind-Issues#19]
The filename of a card script is obtained by replacing all non-alphanumeric characters with _. This includes the hyphen.

Eg. in https://code.google.com/r/projectfiremind-magarena-20140421/source/detail?r=183fb087149e6251cd609db51d085eaee2f14dcc
the correct filename should be Ghitu_Fire_Eater.txt and Ghitu_Fire_Eater.groovy

**Comment by firemind** [comment]
I just changed the regexp for escaping to the one Magarena uses .gsub(/[^A-Za-z0-9]/, "_")
