### ISSUE TITLE
fix wrong card images

### ISSUE THREAD

**Issue by firemind** [firemind/ProjectFiremind-Issues#25]
Some cards have plain wrong images (like mox jet). Figure out if there is a pattern and an easy fix. If not maybe let users report broken images.

**Comment by firemind** [comment]
I re-downloaded the blocks with broken images and haven't seen a wrong one in a while. Seems to be fixed.

**Comment by PalladiaMors** [comment]
Pictures from the set Stronghold still seem to be scrambled.
