### ISSUE TITLE
Push card scripts to github instead of googlecode starting from Nov

### ISSUE THREAD

**Issue by melvinzhang** [firemind/ProjectFiremind-Issues#27]
We intend to switch over from hg hosted on googlecode to git hosted on github after the Oct dev cycle. Starting Nov, we'll start to use the github repository as the main repo. Hopefully the card submission can be updated as well.

**Comment by melvinzhang** [comment]
Saw that you started to push submissions to a clone, nice work!

I noticed that the username of the user who submitted the card is in the commit message instead of the author field. I think it would be clearer to have the username as the author, using the --author parameter of the commit command.

Also will allow us to use scripts to extract the list of authors for each release automatically.

**Comment by firemind** [comment]
I changed that accordingly. Let me know once the hg worker can be shut down.

**Comment by melvinzhang** [comment]
Thanks, look good. So far we are on schedule, currently we are still using hg for development. The switch is planned to coincide with 1.55 release announcement. Will update here as well.

**Comment by melvinzhang** [comment]
hg workers can be shut down now. Thanks!

**Comment by melvinzhang** [comment]
Just rebased the new card submissions onto master, working well!
