### ISSUE TITLE
status shows pushed but repo not updated

### ISSUE THREAD

**Issue by melvinzhang** [firemind/ProjectFiremind-Issues#30]
On https://www.firemind.ch/status there are some new cards that were shown as pushed, eg https://www.firemind.ch/card_script_submissions/2813 but I'm unable to find the commit on the csm-auto repo.

Btw, nice work on the automatic testing of the submissions! I noticed some of the improper submissions were correctly rejected by the system.

**Comment by firemind** [comment]
I just ran the push worker again for the last commits (id 2813 and forward). The most recent one (Izzet Charm) was pushed first as a test, that is why it's out of order.

They all seem to be pushed to the master branch now.

**Comment by melvinzhang** [comment]
Looks good. Thanks!
