### ISSUE TITLE
Archetype Identity

### ISSUE THREAD

**Issue by ShawnieBoy** [firemind/ProjectFiremind-Issues#36]
Just a thought about the current Archetype method.

I feel as though Basic lands shouldn't be included in defining an Archetype (and maybe even non-basic lands)

Basic lands are the main card type that can appear in high quantities in a deck, though they rarely define what that deck does. 

Currently 8-Rack is being defined for all mono-black decks, as they contain Swamps. Even though they don't contain any of the non-basic land cards for that archetype.

Some examples from the top 10 Modern decks which are all 8-Rack:

[Wraith Rat](https://www.firemind.ch/deck_lists/10334) - Cards matched = Swamp
[Black and Forth](https://www.firemind.ch/deck_lists/8047) - Cards matched = Swamp
[Poison](https://www.firemind.ch/deck_lists/3689) - Cards matched = Urborg, Tomb of Yawmoth; Swamp

**Comment by firemind** [comment]
Thanks for the feedback. You're obviously right about the number of miss-classifications under the current system.

I am working on a new system using a neural net to learn decks which have been tagged by users. If you press on the "change" link under an archetype you can give your own classification or even suggest a new archetype. So if you see a miss-classified deck please fix it. I'll be training the neural net some time this week and use it to reclassify every deck on firemind. After that I'll probably compile the new user tagged decks every week to re-train the NN.

**Comment by ShawnieBoy** [comment]
Nice - Will be interested to see that :+1:

**Comment by firemind** [comment]
Classification NN is up now. Error rate is around 5%

I will be updating it regularly with new information given by users (change link below Archetype -> Human Archetype).
