### ISSUE TITLE
can't open a duel

### ISSUE THREAD

**Issue by Muppet1** [firemind/ProjectFiremind-Issues#37]
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

logged in as Ian Hodges. deck merfolk under modern.  click the deck.  page opens click modern under challenge the above error appears.

using i.e.11 on windows 10.

**Comment by Muppet1** [comment]
tried making new deck and clicking various other decks all give same error if I find some way to start a duel i'll post again.

**Comment by Muppet1** [comment]
Ok if I click run a duel and then find  another deck to play it will run.  So its just the challenge part not working.

**Comment by firemind** [comment]
Thanks again for the report. It's fixed now as described in http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=14985&start=105#p192809
