### ISSUE TITLE
Are you willing to open source some of this?

### ISSUE THREAD

**Issue by bmkelly** [firemind/ProjectFiremind-Issues#38]
Or share with the strict requirement of no further sharing?

I'd like to look/reuse how you automate games between AI.  I'm looking into deep RL/machine learning techniques, and this would provide a great starting point for training AI.

**Comment by firemind** [comment]
All game processing is done within the Magarena engine which is already open source: https://github.com/magarena/magarena

I just extended it to fetch games from the firemind API and post the results back. So I'd suggest having a look at that.

The only part of ProjectFiremind that does anything AI related and isn't open source is the neural net I use to classify deck archetypes. It's pretty basic and needs some cleanup and docs which is the only reason I haven't open sourced it yet.
