### ISSUE TITLE
Illegal Legal Deck in Modern

### ISSUE THREAD

**Issue by ShawnieBoy** [firemind/ProjectFiremind-Issues#40]
My Modern [deck](https://www.firemind.ch/decks/156981) is showing that [Longshot Squad](http://gatherer.wizards.com/Pages/Card/Printings.aspx?multiverseid=386588) isn't Modern legal. It is.

**Comment by firemind** [comment]
Thanks for catching this. 

When I added the SOI cards I didn't recalculate the format legalities accordingly which lead to seemingly random cards being flagged as not legal.  I rotated the formats now. Unfortunately your deck (and many others) didn't get migrated to new modern. This shows in the deck currently being placed in "Modern SOI" 

I'm currently checking for all decks if they are legal in the current version of their format and if so move them there. This will take some time though. 

If you can't wait to run duels with it you can always manually change the format to new Modern.
