### ISSUE TITLE
Assigned Clusters are only updated after closing the pop-up

### ISSUE THREAD

**Issue by pshem** [firemind/ProjectFiremind-Issues#45]
To replicate:
1. Create a cluster:
![clustered](https://user-images.githubusercontent.com/26800787/41356819-f56fe870-6f24-11e8-9134-d02cb1d1626a.png)
2. Try to assign cards to a cluster. You assignments aren't shown until you re-open the pop-up
![clusters2](https://user-images.githubusercontent.com/26800787/41356905-33a21938-6f25-11e8-94c6-2dca66110ea9.png)

This initially made me think the functionality was broken.

**Comment by firemind** [comment]
Thanks for the report. I actually forgot that feature existed.

Let me know if you have suggestions on how to improve it. Took me a second to figure out what it was even good for.

The bug is fixed now.
