### ISSUE TITLE
Classify Archeotype of each uploaded deck

### ISSUE THREAD

**Issue by pshem** [firemind/ProjectFiremind-Issues#47]
Currently there is a way to [get your deck archeotype classified](https://www.firemind.ch/archetypes/classify) by project firemind, but its not automatically applied to newly created decks, even as a suggestion. As a result, about 23% of decks in Standard, Modern and Pauper, 28% in Vintage and 42% in Legacy don't have an Archeotype.

Suggestion: appy the classification automatically to each uploaded deck

**Comment by pshem** [comment]
Also, the archeotype is reset to no archeotype whenever you update the decklist, probably because decks are actually immutable. It would be useful if decks kept their archeotype when their decklists are changed, because you usually don't change the archeotype when tweaking a deck

**Comment by firemind** [comment]
This actually happens already. I just messed up and set the threshold for model confidence way too high when I updated the model recently which caused almost all decks to be classified as "No Archetype". It should be fixed now though I might still to tweak the threshold.
