### ISSUE TITLE
Display daily 5-0 and daily 4-1 in archeotype statistics

### ISSUE THREAD

**Issue by pshem** [firemind/ProjectFiremind-Issues#48]
The archeotype statistics pages [such as this one](https://www.firemind.ch/archetypes/4479) seem to not have been updated since the default game consisted of 4 battles. As games by default consist of 5 battles now, no battles are shown in the last 4-0 and 3-1 results pages.

![Screenshot](https://screenshotscdn.firefoxusercontent.com/images/2d4f055b-b927-4acd-a3a6-edea42959fd3.png)
Changing those to daily 5-0 and daily 4-1 could make those statistics work again.

**Comment by firemind** [comment]
That statistic is actually based on the MTGO results WotC publishes. Obviously the dailies have been replaced by leagues for a while now and I should probably display those results instead.

**Comment by pshem** [comment]
Oh, I thought they were from Firemind results ;)

**Comment by firemind** [comment]
I changed it to display 5-0 results in competitive leagues and 7-0 results in challenges. I also updated the title to make it a bit clearer where the results come from.

**Comment by pshem** [comment]
That's perfect!  :1st_place_medal:  Thank you :+1:
