### ISSUE TITLE
Card Request Page

### ISSUE THREAD

**Issue by ShawnieBoy** [firemind/ProjectFiremind-Issues#8]
Cards that have been requested, and then added, still appear on the card request list

**Comment by ShawnieBoy** [comment]
Additionally, a card script can be requested for a different edition of a card that's already been implemented

**Comment by firemind** [comment]
Thanks for catching that. I added code to delete the card requests when the card is being enabled. I also cleaned up the existing requests.

The second issue is part of a bigger problem with cards in different editions. I hope to fix this soon.
